(function (global) {
  const DEFAULT_TRIP_COVER = "assets/trip-cover-placeholder.svg";
  const DEFAULT_PLACE_COVER = "assets/home-aurora-cover.svg";
  const photo = (id) => `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=900&q=80`;
  const flickr = (query, lock) => `https://loremflickr.com/900/600/${query}?lock=${lock}`;
  const REAL_PHOTOS = {
    default: photo("1500530855697-b586d89ba3ee"),
    city: photo("1502602898657-3e91760cbb34"),
    coast: photo("1507525428034-b723cf961d3e"),
    nature: photo("1469474968028-56623f02e42e"),
    aurora: photo("1519681393784-d120267933ba"),
    desert: photo("1500534314209-a25ddb2bd429"),
    safari: photo("1518548419970-58e3b4079ab2"),
    mountain: photo("1506744038136-46273834b3fb"),
    history: photo("1523906834658-6e24ef2386f9"),
    island: photo("1507525428034-b723cf961d3e"),
    roadtrip: photo("1500534623283-312aade485b7"),
    museum: photo("1528127269322-539801943592"),
  };
  const COUNTRY_PHOTOS = {
    ES: photo("1583422409516-2895a77efded"),
    PT: photo("1505761671935-60b3a7427bad"),
    GB: photo("1513635269975-59663e0ac1ad"),
    DE: photo("1467269204594-9661b134dd2b"),
    CH: photo("1506744038136-46273834b3fb"),
    AT: photo("1500530855697-b586d89ba3ee"),
    DK: photo("1513622470522-26c3c8a854bc"),
    HR: photo("1523906834658-6e24ef2386f9"),
    MA: photo("1500534314209-a25ddb2bd429"),
    ZA: photo("1580060839134-75a5edca2e99"),
    US: photo("1501594907352-04cda38ebc29"),
    CA: photo("1506744038136-46273834b3fb"),
    MX: photo("1518638150340-f706e86654de"),
    BR: photo("1483729558449-99ef09a8c325"),
    AR: photo("1500530855697-b586d89ba3ee"),
    PE: photo("1526392060635-9d6019884377"),
    AU: photo("1500530855697-b586d89ba3ee"),
    NZ: photo("1469474968028-56623f02e42e"),
    CN: photo("1508804185872-d7badad00f7d"),
    ID: photo("1537996194471-e657df975ab4"),
    PH: photo("1518509562904-e7ef99cdcc86"),
    IN: photo("1524492412937-b28074a5d7da"),
    NP: photo("1500530855697-b586d89ba3ee"),
    LK: photo("1500530855697-b586d89ba3ee"),
    MV: photo("1507525428034-b723cf961d3e"),
    JO: photo("1500534314209-a25ddb2bd429"),
    GE: photo("1500530855697-b586d89ba3ee"),
    NL: photo("1512470876302-972faa2aa9a4"),
    BE: photo("1528127269322-539801943592"),
    IE: photo("1476514525535-07fb3b4ae5f1"),
    CZ: photo("1541849546-216549ae216d"),
    HU: photo("1549877452-9c387954fbc2"),
    SI: photo("1506744038136-46273834b3fb"),
    NA: photo("1500534314209-a25ddb2bd429"),
    CL: photo("1500530855697-b586d89ba3ee"),
  };
  const CITY_PHOTOS = {
    "JP-TYO": photo("1540959733332-eab4deabeeaf"),
    "JP-KYO": photo("1493976040374-85c8e12f0c0e"),
    "JP-OSA": photo("1590559899731-a382839e5549"),
    "JP-SPK": photo("1516822003754-cca485356ecb"),
    "JP-NAR": photo("1528360983277-13d401cdc186"),
    "JP-YOK": photo("1536098561742-ca998e48cbcc"),
    "JP-KOB": photo("1558862107-d49ef2a04d72"),
    "JP-FUK": photo("1578469645742-46cae010e5d4"),
    "JP-HIR": photo("1542051841857-5f90071e7989"),
    "JP-NGO": photo("1528164344705-47542687000d"),
    "JP-NAH": photo("1507525428034-b723cf961d3e"),
    "JP-KMK": photo("1513407030348-c983a97b98d8"),
    "ES-BCN": photo("1583422409516-2895a77efded"),
    "ES-MAD": photo("1539037116277-4db20889f2d4"),
    "PT-LIS": photo("1505761671935-60b3a7427bad"),
    "GB-LON": photo("1513635269975-59663e0ac1ad"),
    "GB-EDI": photo("1500530855697-b586d89ba3ee"),
    "DE-BER": photo("1467269204594-9661b134dd2b"),
    "CH-INT": photo("1506744038136-46273834b3fb"),
    "DK-CPH": photo("1513622470522-26c3c8a854bc"),
    "HR-DBV": photo("1523906834658-6e24ef2386f9"),
    "MA-MRK": photo("1500534314209-a25ddb2bd429"),
    "ZA-CPT": photo("1580060839134-75a5edca2e99"),
    "US-NYC": photo("1501594907352-04cda38ebc29"),
    "US-SFO": photo("1500534623283-312aade485b7"),
    "CA-BAN": photo("1506744038136-46273834b3fb"),
    "MX-MEX": photo("1518638150340-f706e86654de"),
    "PE-CUS": photo("1526392060635-9d6019884377"),
    "ID-DPS": photo("1537996194471-e657df975ab4"),
    "PH-CEB": photo("1518509562904-e7ef99cdcc86"),
    "IN-AGR": photo("1524492412937-b28074a5d7da"),
    "JO-PET": photo("1500534314209-a25ddb2bd429"),
    "NA-SOS": photo("1500534314209-a25ddb2bd429"),
    "NZ-QUE": photo("1469474968028-56623f02e42e"),
    "AU-SYD": photo("1500530855697-b586d89ba3ee"),
  };
  const CONTINENT_PHOTOS = {
    "东亚": photo("1508804185872-d7badad00f7d"),
    "东南亚": photo("1537996194471-e657df975ab4"),
    "南亚": photo("1524492412937-b28074a5d7da"),
    "西亚": photo("1500534314209-a25ddb2bd429"),
    "中亚": photo("1506744038136-46273834b3fb"),
    "北欧": photo("1519681393784-d120267933ba"),
    "西欧": photo("1502602898657-3e91760cbb34"),
    "中欧": photo("1541849546-216549ae216d"),
    "东欧": photo("1541849546-216549ae216d"),
    "南欧": photo("1523906834658-6e24ef2386f9"),
    "北非": photo("1500534314209-a25ddb2bd429"),
    "东非": photo("1518548419970-58e3b4079ab2"),
    "南非": photo("1580060839134-75a5edca2e99"),
    "西非": photo("1500530855697-b586d89ba3ee"),
    "中非": photo("1518548419970-58e3b4079ab2"),
    "北美洲": photo("1501594907352-04cda38ebc29"),
    "南美洲": photo("1526392060635-9d6019884377"),
    "大洋洲": photo("1469474968028-56623f02e42e"),
  };

  function isDefaultCover(cover) {
    return !cover || cover === DEFAULT_PLACE_COVER || cover === DEFAULT_TRIP_COVER;
  }

  function needsRealPhoto(cover) {
    return isDefaultCover(cover) || /\.svg(?:$|\?)/.test(String(cover || ""));
  }

  function countryPhoto(id, cover, continent, name = "", englishName = "") {
    if (!isDefaultCover(cover)) return cover;
    return COUNTRY_PHOTOS[id] || CONTINENT_PHOTOS[continent] || REAL_PHOTOS.default;
  }

  function countryRasterPhoto(id) {
    const row = COUNTRY_ROWS.find((country) => country[0] === id);
    const cover = row?.[4];
    if (cover && !needsRealPhoto(cover)) return cover;
    return COUNTRY_PHOTOS[id] || CONTINENT_PHOTOS[row?.[3]] || "";
  }

  const COUNTRY_ROWS = [
    ["JP", "日本", "Japan", "东亚", "assets/country-landmark-japan.jpg"],
    ["KR", "韩国", "South Korea", "东亚", "assets/country-landmark-korea.jpg"],
    ["TH", "泰国", "Thailand", "东南亚", "assets/country-landmark-thailand.jpg"],
    ["SG", "新加坡", "Singapore", "东南亚", "assets/country-landmark-singapore.jpg"],
    ["MY", "马来西亚", "Malaysia", "东南亚", "assets/country-landmark-malaysia.jpg"],
    ["VN", "越南", "Vietnam", "东南亚", "assets/country-landmark-vietnam.jpg"],
    ["KH", "柬埔寨", "Cambodia", "东南亚", "assets/country-landmark-cambodia.jpg"],
    ["TR", "土耳其", "Turkey", "西亚", "assets/country-landmark-turkey.jpg"],
    ["AE", "阿联酋", "United Arab Emirates", "西亚", "assets/country-landmark-uae.jpg"],
    ["EG", "埃及", "Egypt", "北非", "assets/country-landmark-egypt.jpg"],
    ["FR", "法国", "France", "西欧", "assets/country-landmark-france.jpg"],
    ["IT", "意大利", "Italy", "南欧", "assets/country-landmark-italy.jpg"],
    ["ES", "西班牙", "Spain", "南欧", DEFAULT_PLACE_COVER],
    ["PT", "葡萄牙", "Portugal", "南欧", DEFAULT_PLACE_COVER],
    ["GR", "希腊", "Greece", "南欧", "assets/country-landmark-greece.jpg"],
    ["GB", "英国", "United Kingdom", "北欧", DEFAULT_PLACE_COVER],
    ["DE", "德国", "Germany", "西欧", DEFAULT_PLACE_COVER],
    ["CH", "瑞士", "Switzerland", "西欧", DEFAULT_PLACE_COVER],
    ["AT", "奥地利", "Austria", "西欧", DEFAULT_PLACE_COVER],
    ["NO", "挪威", "Norway", "北欧", "assets/country-landmark-norway.jpg"],
    ["FI", "芬兰", "Finland", "北欧", "assets/country-landmark-finland.png"],
    ["SE", "瑞典", "Sweden", "北欧", "assets/country-landmark-sweden.jpg"],
    ["DK", "丹麦", "Denmark", "北欧", DEFAULT_PLACE_COVER],
    ["IS", "冰岛", "Iceland", "北欧", "assets/country-landmark-iceland.jpg"],
    ["HR", "克罗地亚", "Croatia", "南欧", DEFAULT_PLACE_COVER],
    ["BA", "波黑", "Bosnia and Herzegovina", "南欧", DEFAULT_PLACE_COVER],
    ["RS", "塞尔维亚", "Serbia", "南欧", DEFAULT_PLACE_COVER],
    ["ME", "黑山", "Montenegro", "南欧", DEFAULT_PLACE_COVER],
    ["UZ", "乌兹别克斯坦", "Uzbekistan", "中亚", "assets/country-landmark-uzbekistan.jpg"],
    ["KZ", "哈萨克斯坦", "Kazakhstan", "中亚", "assets/country-landmark-kazakhstan.jpg"],
    ["KG", "吉尔吉斯斯坦", "Kyrgyzstan", "中亚", "assets/country-landmark-kyrgyzstan.jpg"],
    ["MA", "摩洛哥", "Morocco", "北非", DEFAULT_PLACE_COVER],
    ["KE", "肯尼亚", "Kenya", "东非", "assets/country-landmark-kenya.jpg"],
    ["TZ", "坦桑尼亚", "Tanzania", "东非", "assets/country-landmark-tanzania.jpg"],
    ["ZA", "南非", "South Africa", "南非", DEFAULT_PLACE_COVER],
    ["US", "美国", "United States", "北美洲", DEFAULT_PLACE_COVER],
    ["CA", "加拿大", "Canada", "北美洲", DEFAULT_PLACE_COVER],
    ["MX", "墨西哥", "Mexico", "北美洲", DEFAULT_PLACE_COVER],
    ["BR", "巴西", "Brazil", "南美洲", DEFAULT_PLACE_COVER],
    ["AR", "阿根廷", "Argentina", "南美洲", DEFAULT_PLACE_COVER],
    ["PE", "秘鲁", "Peru", "南美洲", DEFAULT_PLACE_COVER],
    ["AU", "澳大利亚", "Australia", "大洋洲", DEFAULT_PLACE_COVER],
    ["NZ", "新西兰", "New Zealand", "大洋洲", DEFAULT_PLACE_COVER],
    ["CN", "中国", "China", "东亚", DEFAULT_PLACE_COVER],
    ["MN", "蒙古", "Mongolia", "东亚", DEFAULT_PLACE_COVER],
    ["ID", "印度尼西亚", "Indonesia", "东南亚", DEFAULT_PLACE_COVER],
    ["PH", "菲律宾", "Philippines", "东南亚", DEFAULT_PLACE_COVER],
    ["LA", "老挝", "Laos", "东南亚", DEFAULT_PLACE_COVER],
    ["MM", "缅甸", "Myanmar", "东南亚", DEFAULT_PLACE_COVER],
    ["BN", "文莱", "Brunei", "东南亚", DEFAULT_PLACE_COVER],
    ["TL", "东帝汶", "Timor-Leste", "东南亚", DEFAULT_PLACE_COVER],
    ["IN", "印度", "India", "南亚", DEFAULT_PLACE_COVER],
    ["NP", "尼泊尔", "Nepal", "南亚", DEFAULT_PLACE_COVER],
    ["LK", "斯里兰卡", "Sri Lanka", "南亚", DEFAULT_PLACE_COVER],
    ["MV", "马尔代夫", "Maldives", "南亚", DEFAULT_PLACE_COVER],
    ["BD", "孟加拉国", "Bangladesh", "南亚", DEFAULT_PLACE_COVER],
    ["BT", "不丹", "Bhutan", "南亚", DEFAULT_PLACE_COVER],
    ["PK", "巴基斯坦", "Pakistan", "南亚", DEFAULT_PLACE_COVER],
    ["SA", "沙特阿拉伯", "Saudi Arabia", "西亚", DEFAULT_PLACE_COVER],
    ["QA", "卡塔尔", "Qatar", "西亚", DEFAULT_PLACE_COVER],
    ["JO", "约旦", "Jordan", "西亚", DEFAULT_PLACE_COVER],
    ["GE", "格鲁吉亚", "Georgia", "西亚", DEFAULT_PLACE_COVER],
    ["IL", "以色列", "Israel", "西亚", DEFAULT_PLACE_COVER],
    ["OM", "阿曼", "Oman", "西亚", DEFAULT_PLACE_COVER],
    ["NL", "荷兰", "Netherlands", "西欧", DEFAULT_PLACE_COVER],
    ["BE", "比利时", "Belgium", "西欧", DEFAULT_PLACE_COVER],
    ["LU", "卢森堡", "Luxembourg", "西欧", DEFAULT_PLACE_COVER],
    ["IE", "爱尔兰", "Ireland", "西欧", DEFAULT_PLACE_COVER],
    ["LI", "列支敦士登", "Liechtenstein", "西欧", DEFAULT_PLACE_COVER],
    ["MC", "摩纳哥", "Monaco", "西欧", DEFAULT_PLACE_COVER],
    ["AD", "安道尔", "Andorra", "西欧", DEFAULT_PLACE_COVER],
    ["PL", "波兰", "Poland", "中欧", DEFAULT_PLACE_COVER],
    ["CZ", "捷克", "Czechia", "中欧", DEFAULT_PLACE_COVER],
    ["HU", "匈牙利", "Hungary", "中欧", DEFAULT_PLACE_COVER],
    ["SK", "斯洛伐克", "Slovakia", "中欧", DEFAULT_PLACE_COVER],
    ["SI", "斯洛文尼亚", "Slovenia", "中欧", DEFAULT_PLACE_COVER],
    ["RO", "罗马尼亚", "Romania", "东欧", DEFAULT_PLACE_COVER],
    ["BG", "保加利亚", "Bulgaria", "东欧", DEFAULT_PLACE_COVER],
    ["MD", "摩尔多瓦", "Moldova", "东欧", DEFAULT_PLACE_COVER],
    ["UA", "乌克兰", "Ukraine", "东欧", DEFAULT_PLACE_COVER],
    ["BY", "白俄罗斯", "Belarus", "东欧", DEFAULT_PLACE_COVER],
    ["LT", "立陶宛", "Lithuania", "东欧", DEFAULT_PLACE_COVER],
    ["LV", "拉脱维亚", "Latvia", "东欧", DEFAULT_PLACE_COVER],
    ["EE", "爱沙尼亚", "Estonia", "东欧", DEFAULT_PLACE_COVER],
    ["AL", "阿尔巴尼亚", "Albania", "南欧", DEFAULT_PLACE_COVER],
    ["MK", "北马其顿", "North Macedonia", "南欧", DEFAULT_PLACE_COVER],
    ["XK", "科索沃", "Kosovo", "南欧", DEFAULT_PLACE_COVER],
    ["SM", "圣马力诺", "San Marino", "南欧", DEFAULT_PLACE_COVER],
    ["VA", "梵蒂冈", "Vatican City", "南欧", DEFAULT_PLACE_COVER],
    ["MT", "马耳他", "Malta", "南欧", DEFAULT_PLACE_COVER],
    ["CY", "塞浦路斯", "Cyprus", "南欧", DEFAULT_PLACE_COVER],
    ["CU", "古巴", "Cuba", "北美洲", DEFAULT_PLACE_COVER],
    ["JM", "牙买加", "Jamaica", "北美洲", DEFAULT_PLACE_COVER],
    ["BS", "巴哈马", "Bahamas", "北美洲", DEFAULT_PLACE_COVER],
    ["DO", "多米尼加", "Dominican Republic", "北美洲", DEFAULT_PLACE_COVER],
    ["HT", "海地", "Haiti", "北美洲", DEFAULT_PLACE_COVER],
    ["CR", "哥斯达黎加", "Costa Rica", "北美洲", DEFAULT_PLACE_COVER],
    ["PA", "巴拿马", "Panama", "北美洲", DEFAULT_PLACE_COVER],
    ["GT", "危地马拉", "Guatemala", "北美洲", DEFAULT_PLACE_COVER],
    ["BZ", "伯利兹", "Belize", "北美洲", DEFAULT_PLACE_COVER],
    ["HN", "洪都拉斯", "Honduras", "北美洲", DEFAULT_PLACE_COVER],
    ["SV", "萨尔瓦多", "El Salvador", "北美洲", DEFAULT_PLACE_COVER],
    ["NI", "尼加拉瓜", "Nicaragua", "北美洲", DEFAULT_PLACE_COVER],
    ["PR", "波多黎各", "Puerto Rico", "北美洲", DEFAULT_PLACE_COVER],
    ["TT", "特立尼达和多巴哥", "Trinidad and Tobago", "北美洲", DEFAULT_PLACE_COVER],
    ["BB", "巴巴多斯", "Barbados", "北美洲", DEFAULT_PLACE_COVER],
    ["AG", "安提瓜和巴布达", "Antigua and Barbuda", "北美洲", DEFAULT_PLACE_COVER],
    ["LC", "圣卢西亚", "Saint Lucia", "北美洲", DEFAULT_PLACE_COVER],
    ["GD", "格林纳达", "Grenada", "北美洲", DEFAULT_PLACE_COVER],
    ["VC", "圣文森特和格林纳丁斯", "Saint Vincent and the Grenadines", "北美洲", DEFAULT_PLACE_COVER],
    ["DM", "多米尼克", "Dominica", "北美洲", DEFAULT_PLACE_COVER],
    ["CL", "智利", "Chile", "南美洲", DEFAULT_PLACE_COVER],
    ["CO", "哥伦比亚", "Colombia", "南美洲", DEFAULT_PLACE_COVER],
    ["EC", "厄瓜多尔", "Ecuador", "南美洲", DEFAULT_PLACE_COVER],
    ["BO", "玻利维亚", "Bolivia", "南美洲", DEFAULT_PLACE_COVER],
    ["UY", "乌拉圭", "Uruguay", "南美洲", DEFAULT_PLACE_COVER],
    ["PY", "巴拉圭", "Paraguay", "南美洲", DEFAULT_PLACE_COVER],
    ["VE", "委内瑞拉", "Venezuela", "南美洲", DEFAULT_PLACE_COVER],
    ["GY", "圭亚那", "Guyana", "南美洲", DEFAULT_PLACE_COVER],
    ["SR", "苏里南", "Suriname", "南美洲", DEFAULT_PLACE_COVER],
    ["DZ", "阿尔及利亚", "Algeria", "北非", DEFAULT_PLACE_COVER],
    ["TN", "突尼斯", "Tunisia", "北非", DEFAULT_PLACE_COVER],
    ["LY", "利比亚", "Libya", "北非", DEFAULT_PLACE_COVER],
    ["SD", "苏丹", "Sudan", "北非", DEFAULT_PLACE_COVER],
    ["ET", "埃塞俄比亚", "Ethiopia", "东非", DEFAULT_PLACE_COVER],
    ["SO", "索马里", "Somalia", "东非", DEFAULT_PLACE_COVER],
    ["DJ", "吉布提", "Djibouti", "东非", DEFAULT_PLACE_COVER],
    ["ER", "厄立特里亚", "Eritrea", "东非", DEFAULT_PLACE_COVER],
    ["UG", "乌干达", "Uganda", "东非", DEFAULT_PLACE_COVER],
    ["RW", "卢旺达", "Rwanda", "东非", DEFAULT_PLACE_COVER],
    ["BI", "布隆迪", "Burundi", "东非", DEFAULT_PLACE_COVER],
    ["SS", "南苏丹", "South Sudan", "东非", DEFAULT_PLACE_COVER],
    ["AO", "安哥拉", "Angola", "南非", DEFAULT_PLACE_COVER],
    ["NA", "纳米比亚", "Namibia", "南非", DEFAULT_PLACE_COVER],
    ["BW", "博茨瓦纳", "Botswana", "南非", DEFAULT_PLACE_COVER],
    ["ZW", "津巴布韦", "Zimbabwe", "南非", DEFAULT_PLACE_COVER],
    ["ZM", "赞比亚", "Zambia", "南非", DEFAULT_PLACE_COVER],
    ["MW", "马拉维", "Malawi", "南非", DEFAULT_PLACE_COVER],
    ["MZ", "莫桑比克", "Mozambique", "南非", DEFAULT_PLACE_COVER],
    ["MG", "马达加斯加", "Madagascar", "南非", DEFAULT_PLACE_COVER],
    ["MU", "毛里求斯", "Mauritius", "南非", DEFAULT_PLACE_COVER],
    ["SC", "塞舌尔", "Seychelles", "南非", DEFAULT_PLACE_COVER],
    ["LS", "莱索托", "Lesotho", "南非", DEFAULT_PLACE_COVER],
    ["SZ", "斯威士兰", "Eswatini", "南非", DEFAULT_PLACE_COVER],
    ["KM", "科摩罗", "Comoros", "南非", DEFAULT_PLACE_COVER],
    ["NG", "尼日利亚", "Nigeria", "西非", DEFAULT_PLACE_COVER],
    ["GH", "加纳", "Ghana", "西非", DEFAULT_PLACE_COVER],
    ["SN", "塞内加尔", "Senegal", "西非", DEFAULT_PLACE_COVER],
    ["CI", "科特迪瓦", "Cote d'Ivoire", "西非", DEFAULT_PLACE_COVER],
    ["NE", "尼日尔", "Niger", "西非", DEFAULT_PLACE_COVER],
    ["ML", "马里", "Mali", "西非", DEFAULT_PLACE_COVER],
    ["BF", "布基纳法索", "Burkina Faso", "西非", DEFAULT_PLACE_COVER],
    ["GN", "几内亚", "Guinea", "西非", DEFAULT_PLACE_COVER],
    ["SL", "塞拉利昂", "Sierra Leone", "西非", DEFAULT_PLACE_COVER],
    ["LR", "利比里亚", "Liberia", "西非", DEFAULT_PLACE_COVER],
    ["GM", "冈比亚", "Gambia", "西非", DEFAULT_PLACE_COVER],
    ["GW", "几内亚比绍", "Guinea-Bissau", "西非", DEFAULT_PLACE_COVER],
    ["TG", "多哥", "Togo", "西非", DEFAULT_PLACE_COVER],
    ["BJ", "贝宁", "Benin", "西非", DEFAULT_PLACE_COVER],
    ["CV", "佛得角", "Cape Verde", "西非", DEFAULT_PLACE_COVER],
    ["MR", "毛里塔尼亚", "Mauritania", "西非", DEFAULT_PLACE_COVER],
    ["CM", "喀麦隆", "Cameroon", "中非", DEFAULT_PLACE_COVER],
    ["GA", "加蓬", "Gabon", "中非", DEFAULT_PLACE_COVER],
    ["CG", "刚果共和国", "Republic of the Congo", "中非", DEFAULT_PLACE_COVER],
    ["CD", "刚果民主共和国", "Democratic Republic of the Congo", "中非", DEFAULT_PLACE_COVER],
    ["CF", "中非共和国", "Central African Republic", "中非", DEFAULT_PLACE_COVER],
    ["TD", "乍得", "Chad", "中非", DEFAULT_PLACE_COVER],
    ["GQ", "赤道几内亚", "Equatorial Guinea", "中非", DEFAULT_PLACE_COVER],
    ["ST", "圣多美和普林西比", "Sao Tome and Principe", "中非", DEFAULT_PLACE_COVER],
    ["FJ", "斐济", "Fiji", "大洋洲", DEFAULT_PLACE_COVER],
    ["PG", "巴布亚新几内亚", "Papua New Guinea", "大洋洲", DEFAULT_PLACE_COVER],
    ["SB", "所罗门群岛", "Solomon Islands", "大洋洲", DEFAULT_PLACE_COVER],
    ["VU", "瓦努阿图", "Vanuatu", "大洋洲", DEFAULT_PLACE_COVER],
    ["NC", "新喀里多尼亚", "New Caledonia", "大洋洲", DEFAULT_PLACE_COVER],
    ["WS", "萨摩亚", "Samoa", "大洋洲", DEFAULT_PLACE_COVER],
    ["TO", "汤加", "Tonga", "大洋洲", DEFAULT_PLACE_COVER],
    ["TV", "图瓦卢", "Tuvalu", "大洋洲", DEFAULT_PLACE_COVER],
    ["KI", "基里巴斯", "Kiribati", "大洋洲", DEFAULT_PLACE_COVER],
    ["FM", "密克罗尼西亚", "Micronesia", "大洋洲", DEFAULT_PLACE_COVER],
    ["PW", "帕劳", "Palau", "大洋洲", DEFAULT_PLACE_COVER],
    ["MH", "马绍尔群岛", "Marshall Islands", "大洋洲", DEFAULT_PLACE_COVER],
  ];

  const GUIDE_BY_COUNTRY = {
    JP: guide("融合传统与现代的国度，四季分明，适合城市漫游、温泉、美食和季节旅行。", "5-8天", "3-5月 / 10-11月", "中高", ["樱花", "城市漫游", "温泉", "美食"], ["富士山", "浅草寺", "伏见稻荷大社", "道顿堀"]),
    KR: guide("城市、美食、购物和海边短线都很集中，适合轻量城市假期。", "4-7天", "3-5月 / 9-11月", "中等", ["城市", "美食", "购物", "展览"], ["景福宫", "明洞", "汉江公园", "海云台"]),
    TH: guide("预算弹性大，海岛、寺庙、夜市和慢旅行都很适合收集。", "5-8天", "11-2月", "中等", ["海岛", "寺庙", "夜市", "慢旅行"], ["大皇宫", "郑王庙", "契迪龙寺", "普吉海滩"]),
    SG: guide("城市尺度小但内容密度高，适合海湾夜景、街区和亲子旅行。", "3-5天", "全年", "中等", ["城市", "海湾夜景", "亲子", "街区"], ["滨海湾花园", "鱼尾狮公园", "圣淘沙", "牛车水"]),
    MY: guide("城市、海岛和多元文化街区组合灵活，适合东南亚延伸。", "5-8天", "按东西海岸季节选择", "中等", ["城市", "海岛", "美食", "多元文化"], ["双子塔", "槟城老城", "兰卡威", "马六甲"]),
    VN: guide("城市、美食、古城和海岸线适合串联，预算友好。", "5-8天", "11-4月", "中等", ["美食", "古城", "海岸", "城市"], ["河内老城", "下龙湾", "会安古城", "胡志明市"]),
    KH: guide("吴哥古迹是核心记忆点，适合和泰国或越南组合。", "3-5天", "11-2月", "中等", ["古迹", "吴哥", "慢旅行"], ["吴哥窟", "巴戎寺", "塔布笼寺"]),
    TR: guide("海峡、古城、热气球和海岸兼具，画面感很强。", "7-10天", "4-6月 / 9-10月", "中等", ["古城", "热气球", "海峡", "市集"], ["圣索菲亚大教堂", "大巴扎", "热气球", "卡莱伊奇老城"]),
    AE: guide("高楼、沙漠、购物和建筑体验集中，适合短暂停留或中东入门。", "3-6天", "11-3月", "中高", ["城市", "建筑", "沙漠", "购物"], ["哈利法塔", "迪拜购物中心", "沙漠冲沙", "谢赫扎耶德大清真寺"]),
    EG: guide("金字塔、尼罗河和古文明遗址集中，适合主题收藏。", "6-10天", "10-4月", "中等", ["金字塔", "古文明", "尼罗河", "遗址"], ["吉萨金字塔", "埃及博物馆", "卡纳克神庙", "卢克索神庙"]),
    FR: guide("博物馆、建筑、美食、小镇和海岸路线都成熟。", "6-10天", "4-6月 / 9-10月", "中高", ["博物馆", "建筑", "美食", "小镇"], ["卢浮宫", "埃菲尔铁塔", "奥赛博物馆", "英国人散步大道"]),
    IT: guide("古城、艺术、美食和海岸线兼具，适合城市串联旅行。", "7-12天", "4-6月 / 9-10月", "中高", ["古城", "艺术", "美食", "海岸"], ["斗兽场", "乌菲兹美术馆", "圣马可广场", "阿马尔菲海岸"]),
    ES: guide("建筑、美食、艺术和南部古城路线都很有辨识度。", "7-12天", "4-6月 / 9-10月", "中等", ["建筑", "美食", "艺术", "海岸"], ["圣家堂", "普拉多博物馆", "塞维利亚王宫"]),
    PT: guide("坡路、电车、海岸和酒庄组成轻松的南欧路线。", "5-8天", "4-6月 / 9-10月", "中等", ["海岸", "老城", "电车", "酒庄"], ["贝伦塔", "阿尔法玛", "路易一世大桥", "辛特拉"]),
    GR: guide("古迹、海岛、日落和蓝白小镇组成典型地中海记忆。", "6-10天", "4-6月 / 9-10月", "中高", ["古迹", "海岛", "日落", "蓝白小镇"], ["雅典卫城", "卫城博物馆", "伊亚日落", "梅黛奥拉"]),
    GB: guide("博物馆、剧院、古城和湖区自然线都适合串联。", "7-10天", "5-9月", "中高", ["博物馆", "古城", "戏剧", "湖区"], ["大英博物馆", "塔桥", "爱丁堡城堡", "湖区"]),
    DE: guide("城市、博物馆、城堡和森林湖区构成稳定的欧洲路线。", "7-10天", "5-10月", "中高", ["城市", "博物馆", "城堡", "森林"], ["博物馆岛", "勃兰登堡门", "新天鹅堡", "国王湖"]),
    CH: guide("湖区、雪山、火车和徒步体验集中，预算偏高但稳定。", "6-9天", "6-9月 / 12-3月", "高", ["雪山", "湖区", "火车", "徒步"], ["苏黎世湖", "卡佩尔廊桥", "少女峰", "马特洪峰"]),
    AT: guide("宫殿、音乐、咖啡馆和湖区雪山适合慢节奏串联。", "5-8天", "5-10月", "中高", ["古典音乐", "宫殿", "湖区", "咖啡馆"], ["美泉宫", "金色大厅", "萨尔茨堡城堡", "哈尔施塔特"]),
    NO: guide("峡湾、城市设计和北境自然感并存，适合作为北欧路线起点。", "5-9天", "6-9月 / 12-3月", "高", ["峡湾", "极光", "设计", "海岸"], ["奥斯陆歌剧院", "峡湾游船", "维格兰雕塑公园"]),
    FI: guide("湖区、桑拿、设计和冬季雪地体验构成轻松北欧路线。", "4-7天", "6-9月 / 12-3月", "高", ["湖区", "桑拿", "设计", "极光"], ["赫尔辛基大教堂", "设计区", "拉普兰雪地"]),
    SE: guide("城市设计、群岛和老城氛围适合北欧慢游。", "4-7天", "5-9月", "高", ["设计", "群岛", "老城", "自然"], ["斯德哥尔摩老城", "瓦萨博物馆", "群岛游船"]),
    IS: guide("火山、瀑布、冰川和极光集中，适合自然风景主题旅行。", "5-8天", "6-9月 / 9-3月", "高", ["极光", "冰川", "瀑布", "自驾"], ["黄金圈", "黑沙滩", "蓝湖", "冰川湖"]),
    UZ: guide("丝路古城和清真寺建筑集中，适合文化主题收集。", "6-8天", "4-5月 / 9-10月", "中等", ["丝路", "古城", "清真寺", "市集"], ["撒马尔罕", "布哈拉", "希瓦古城"]),
    MA: guide("古城、市集、蓝城和沙漠构成强烈色彩记忆。", "6-9天", "3-5月 / 9-11月", "中等", ["古城", "沙漠", "市集", "蓝城"], ["德吉玛广场", "菲斯老城", "舍夫沙万老城", "撒哈拉沙丘"]),
    KE: guide("东非 Safari 代表，草原和动物迁徙主题突出。", "6-9天", "7-10月", "中高", ["Safari", "草原", "动物", "自然"], ["内罗毕国家公园", "马赛马拉保护区", "马拉河"]),
    TZ: guide("草原、火山和海岛组合，适合自然主题路线。", "6-10天", "6-10月", "中高", ["Safari", "草原", "海岛", "自然"], ["塞伦盖蒂", "恩戈罗恩戈罗", "乞力马扎罗", "桑给巴尔"]),
    US: guide("城市、国家公园、自驾和演出体验跨度很大。", "7-14天", "按路线季节选择", "高", ["城市", "自驾", "国家公园", "演出"], ["中央公园", "大都会艺术博物馆", "金门大桥", "大峡谷"]),
    CA: guide("落基山、湖区和东部城市适合自然加城市组合。", "7-12天", "6-9月", "高", ["自然", "国家公园", "湖区", "城市"], ["温哥华", "露易丝湖", "尼亚加拉瀑布", "魁北克老城"]),
    AU: guide("海港城市、大堡礁、内陆荒原和公路旅行都很典型。", "7-12天", "9-11月 / 3-5月", "高", ["自驾", "海岸", "自然", "潜水"], ["悉尼歌剧院", "邦迪海滩", "大堡礁", "乌鲁鲁"]),
    NZ: guide("湖区、雪山、自驾和轻徒步组成新西兰核心记忆。", "8-14天", "11-4月", "高", ["自驾", "湖区", "雪山", "徒步"], ["皇后镇", "瓦纳卡湖", "库克山", "蒂卡普湖"]),
  };

  const CITY_ROWS = [
    ["JP-TYO", "东京", "Tokyo", "JP", "assets/city-tokyo-cover.svg", "现代与传统交织的国际化大都市，适合第一次到日本时作为起点。", ["城市", "美食", "展览", "夜景"], ["浅草寺", "涩谷", "明治神宫", "东京塔"]],
    ["JP-KYO", "京都", "Kyoto", "JP", "assets/city-kyoto-cover.svg", "寺庙、庭院和老街集中，适合放慢节奏感受传统日本。", ["古建筑", "庭园", "神社", "慢旅行"], ["清水寺", "伏见稻荷大社", "岚山", "祇园"]],
    ["JP-OSA", "大阪", "Osaka", "JP", "assets/city-osaka-cover.svg", "关西的热闹城市核心，美食、购物和夜晚街区都很集中。", ["美食", "城市", "购物", "夜景"], ["道顿堀", "大阪城", "日本环球影城", "黑门市场"]],
    ["JP-SPK", "札幌", "Sapporo", "JP", "assets/city-sapporo-cover.svg", "北海道门户城市，适合串联小樽、温泉和冬季雪景。", ["雪景", "北海道", "美食"], ["大通公园", "札幌电视塔", "白色恋人公园"]],
    ["JP-NAR", "奈良", "Nara", "JP", "assets/city-nara-cover.svg", "古都和鹿公园气质轻松，适合关西路线延伸。", ["古都", "公园"], ["奈良公园", "东大寺", "春日大社"]],
    ["JP-YOK", "横滨", "Yokohama", "JP", "assets/city-yokohama-cover.svg", "海港、红砖仓库和现代夜景集中，适合从东京短线延伸。", ["海港", "夜景"], ["港未来", "红砖仓库", "中华街"]],
    ["JP-KOB", "神户", "Kobe", "JP", "assets/city-kobe-cover.svg", "海港、山景和异人馆街区轻松，适合关西城市补充。", ["海港", "美食"], ["北野异人馆", "神户港", "六甲山"]],
    ["JP-FUK", "福冈", "Fukuoka", "JP", DEFAULT_PLACE_COVER, "九州门户城市，屋台、美食和海边公园都很适合慢游。", ["美食", "海边"], ["博多屋台", "大濠公园", "太宰府天满宫"]],
    ["JP-HIR", "广岛", "Hiroshima", "JP", DEFAULT_PLACE_COVER, "和平纪念与宫岛短线结合，适合历史和海岛延伸。", ["历史", "海岛"], ["和平纪念公园", "宫岛", "严岛神社"]],
    ["JP-NGO", "名古屋", "Nagoya", "JP", DEFAULT_PLACE_COVER, "中部城市门户，城堡、美食和工艺博物馆适合中转停留。", ["城市", "美食"], ["名古屋城", "热田神宫", "丰田产业技术纪念馆"]],
    ["JP-NAH", "那霸", "Naha", "JP", DEFAULT_PLACE_COVER, "冲绳门户城市，海岛、市场和琉球文化轻松。", ["海岛", "文化"], ["首里城", "国际通", "波上宫"]],
    ["JP-KMK", "镰仓", "Kamakura", "JP", DEFAULT_PLACE_COVER, "海边古寺和小街适合从东京一日或短住慢游。", ["寺庙", "海边"], ["镰仓大佛", "鹤冈八幡宫", "江之电"]],
    ["KR-SEL", "首尔", "Seoul", "KR", "assets/city-seoul-cover.svg", "购物、美食、展览和街区漫游集中。", ["城市", "购物", "美食"], ["景福宫", "明洞", "汉江公园", "圣水洞"]],
    ["KR-PUS", "釜山", "Busan", "KR", "assets/city-busan-cover.svg", "海边城市，适合和首尔组合成短线。", ["海边", "美食"], ["海云台", "甘川文化村", "札嘎其市场"]],
    ["KR-CJU", "济州", "Jeju", "KR", DEFAULT_PLACE_COVER, "火山岛、海岸和轻松自驾节奏突出，适合作为韩国城市线之外的延伸。", ["海岛", "自然"], ["城山日出峰", "汉拿山", "涉地可支"]],
    ["TH-CNX", "清迈", "Chiang Mai", "TH", "assets/country-landmark-thailand.jpg", "适合休闲和慢生活，咖啡、寺庙、夜市都很舒服。", ["寺庙", "夜市", "慢旅行"], ["契迪龙寺", "宁曼路", "清迈夜市"]],
    ["TH-CEI", "清莱", "Chiang Rai", "TH", "assets/city-chiangrai-cover.svg", "适合从清迈延伸，寺庙和北部风景明显。", ["寺庙", "北部"], ["白庙", "蓝庙", "黑庙"]],
    ["TH-HKT", "普吉", "Phuket", "TH", "assets/city-phuket-cover.svg", "泰国海岛度假代表，适合海滩和出海。", ["海岛", "度假"], ["芭东海滩", "皮皮岛", "普吉老镇"]],
    ["TH-KBI", "甲米", "Krabi", "TH", "assets/city-krabi-cover.svg", "山海景观更自然，适合轻度海岛假期。", ["海岛", "自然"], ["奥南海滩", "莱利海滩", "四岛游"]],
    ["SG-SIN", "新加坡", "Singapore", "SG", "assets/city-singapore-cover.svg", "核心城市漫游区域，适合第一次到访。", ["城市", "亲子", "夜景"], ["滨海湾花园", "鱼尾狮公园", "圣淘沙", "牛车水"]],
    ["MY-KUL", "吉隆坡", "Kuala Lumpur", "MY", "assets/city-kuala-lumpur-cover.svg", "马来西亚城市门户，适合转机和城市短停。", ["城市", "美食"], ["双子塔", "茨厂街", "黑风洞"]],
    ["MY-PEN", "槟城", "Penang", "MY", "assets/city-penang-cover.svg", "老城、美食和多元文化集中。", ["老城", "美食"], ["乔治市", "升旗山", "姓氏桥"]],
    ["VN-HAN", "河内", "Hanoi", "VN", "assets/city-hanoi-cover.svg", "越南北部城市门户，老城和美食集中。", ["老城", "美食"], ["还剑湖", "三十六行街", "文庙"]],
    ["KH-REP", "暹粒", "Siem Reap", "KH", "assets/city-siemreap-cover.svg", "吴哥古迹门户城市。", ["古迹", "吴哥"], ["吴哥窟", "巴戎寺", "塔布笼寺"]],
    ["TR-IST", "伊斯坦布尔", "Istanbul", "TR", "assets/city-istanbul-cover.svg", "东西方交汇的城市，清真寺、市集、海峡都集中。", ["古城", "海峡", "市集"], ["圣索菲亚大教堂", "大巴扎", "博斯普鲁斯海峡"]],
    ["TR-CAP", "卡帕多奇亚", "Cappadocia", "TR", "assets/city-cappadocia-cover.svg", "热气球和洞穴酒店体验最突出。", ["热气球", "洞穴"], ["热气球", "格雷梅露天博物馆", "洞穴酒店"]],
    ["TR-ANT", "安塔利亚", "Antalya", "TR", "assets/city-antalya-cover.svg", "地中海海岸城市，适合放松和自驾。", ["海岸", "老城"], ["卡莱伊奇老城", "杜登瀑布", "地中海海岸"]],
    ["AE-DXB", "迪拜", "Dubai", "AE", "assets/city-dubai-cover.svg", "高楼、购物、海滩和沙漠体验集中。", ["城市", "沙漠"], ["哈利法塔", "迪拜购物中心", "沙漠冲沙"]],
    ["AE-AUH", "阿布扎比", "Abu Dhabi", "AE", "assets/city-abudhabi-cover.svg", "更适合建筑、美术馆和主题乐园。", ["建筑", "展览"], ["谢赫扎耶德大清真寺", "卢浮宫阿布扎比", "法拉利世界"]],
    ["EG-CAI", "开罗", "Cairo", "EG", "assets/city-cairo-cover.svg", "金字塔和博物馆是埃及初访核心。", ["金字塔", "博物馆"], ["吉萨金字塔", "埃及博物馆", "哈利利市场"]],
    ["EG-GLZ", "吉萨", "Giza", "EG", "assets/city-giza-cover.svg", "金字塔群所在地，古文明画面最集中。", ["金字塔", "遗址"], ["吉萨金字塔", "狮身人面像", "太阳船博物馆"]],
    ["EG-LXR", "卢克索", "Luxor", "EG", "assets/city-luxor-cover.svg", "神庙和帝王谷密度极高，适合古埃及爱好者。", ["神庙", "遗址"], ["卡纳克神庙", "帝王谷", "卢克索神庙"]],
    ["FR-PAR", "巴黎", "Paris", "FR", "assets/city-paris-cover.svg", "法国初访核心，博物馆、街区、美食和购物都集中。", ["博物馆", "建筑"], ["卢浮宫", "埃菲尔铁塔", "奥赛博物馆", "蒙马特"]],
    ["FR-NCE", "尼斯", "Nice", "FR", "assets/city-nice-cover.svg", "南法海岸落脚点，适合和摩纳哥、埃兹小镇串联。", ["海岸", "老城"], ["英国人散步大道", "老城", "埃兹小镇"]],
    ["IT-ROM", "罗马", "Rome", "IT", "assets/city-rome-cover.svg", "古迹密度很高，适合第一次意大利旅行。", ["古迹", "艺术"], ["斗兽场", "梵蒂冈博物馆", "许愿池"]],
    ["IT-FLR", "佛罗伦萨", "Florence", "IT", "assets/city-florence-cover.svg", "文艺复兴核心城市，适合美术馆和城市步行。", ["艺术", "建筑"], ["乌菲兹美术馆", "圣母百花大教堂", "米开朗琪罗广场"]],
    ["IT-VCE", "威尼斯", "Venice", "IT", "assets/city-venice-cover.svg", "水城体验强，适合 1-2 晚慢慢走。", ["水城", "小岛"], ["圣马可广场", "总督宫", "布拉诺岛"]],
    ["GR-ATH", "雅典", "Athens", "GR", "assets/city-athens-cover.svg", "希腊古迹核心，也是多数海岛线进出门户。", ["古迹", "老城"], ["雅典卫城", "卫城博物馆", "普拉卡老区"]],
    ["NO-OSL", "奥斯陆", "Oslo", "NO", "assets/city-oslo-cover.svg", "挪威首都，峡湾、建筑和博物馆集中。", ["设计", "峡湾", "博物馆"], ["奥斯陆歌剧院", "维格兰雕塑公园", "蒙克美术馆"]],
    ["FI-HEL", "赫尔辛基", "Helsinki", "FI", "assets/country-landmark-finland.png", "芬兰城市门户，设计、海港和桑拿文化轻松。", ["设计", "海港"], ["赫尔辛基大教堂", "设计区", " Suomenlinna"]],
    ["SE-STO", "斯德哥尔摩", "Stockholm", "SE", "assets/city-stockholm-cover.svg", "群岛城市，老城和设计博物馆适合慢游。", ["老城", "群岛"], ["斯德哥尔摩老城", "瓦萨博物馆", "群岛游船"]],
    ["IS-REK", "雷克雅未克", "Reykjavik", "IS", "assets/city-reykjavik-cover.svg", "冰岛旅行的城市门户，适合连接黄金圈、南岸和极光体验。", ["极光", "海港", "温泉"], ["哈尔格林姆教堂", "太阳航海者", "蓝湖"]],
    ["UZ-SKD", "撒马尔罕", "Samarkand", "UZ", "assets/city-samarkand-cover.svg", "丝路古城代表，蓝色穹顶和广场很有记忆点。", ["丝路", "古城"], ["雷吉斯坦广场", "比比哈努姆清真寺", "沙阿辛达"]],
    ["KZ-ALA", "阿拉木图", "Almaty", "KZ", DEFAULT_PLACE_COVER, "山地和城市生活并存，是哈萨克斯坦旅行的轻量门户。", ["山地", "城市"], ["潘菲洛夫公园", "科克托别山", "大阿拉木图湖"]],
    ["KG-BSK", "比什凯克", "Bishkek", "KG", DEFAULT_PLACE_COVER, "适合连接天山、湖区和草原公路旅行。", ["山地", "草原"], ["阿拉套广场", "奥什市场", "阿拉阿查国家公园"]],
    ["KE-NBO", "内罗毕", "Nairobi", "KE", "assets/city-nairobi-cover.svg", "肯尼亚门户，适合连接国家公园和城市体验。", ["Safari", "动物"], ["内罗毕国家公园", "长颈鹿中心", "凯伦故居"]],
    ["TZ-ARK", "阿鲁沙", "Arusha", "TZ", "assets/city-arusha-cover.svg", "坦桑尼亚 Safari 门户，适合连接草原和火山。", ["Safari", "自然"], ["塞伦盖蒂", "恩戈罗恩戈罗", "乞力马扎罗"]],
    ["ES-BCN", "巴塞罗那", "Barcelona", "ES", DEFAULT_PLACE_COVER, "建筑、海岸和街区漫游集中，适合伊比利亚路线起点。", ["建筑", "海岸"], ["圣家堂", "古埃尔公园", "巴特罗之家"]],
    ["ES-MAD", "马德里", "Madrid", "ES", DEFAULT_PLACE_COVER, "博物馆、美食和广场生活集中，适合连接西班牙中南部。", ["博物馆", "美食"], ["普拉多博物馆", "马约尔广场", "丽池公园"]],
    ["PT-LIS", "里斯本", "Lisbon", "PT", DEFAULT_PLACE_COVER, "坡路、电车、老城和海岸短线都很轻松。", ["老城", "电车"], ["贝伦塔", "阿尔法玛", "商业广场"]],
    ["GB-LON", "伦敦", "London", "GB", DEFAULT_PLACE_COVER, "博物馆、剧院、公园和城市经典地标密集。", ["博物馆", "戏剧"], ["大英博物馆", "塔桥", "海德公园"]],
    ["GB-EDI", "爱丁堡", "Edinburgh", "GB", DEFAULT_PLACE_COVER, "古城、城堡和山丘视野适合作为英伦北部记忆点。", ["古城", "城堡"], ["爱丁堡城堡", "皇家英里", "亚瑟王座"]],
    ["DE-BER", "柏林", "Berlin", "DE", DEFAULT_PLACE_COVER, "博物馆、历史地标和街区文化集中。", ["博物馆", "历史"], ["博物馆岛", "勃兰登堡门", "东边画廊"]],
    ["DE-MUC", "慕尼黑", "Munich", "DE", DEFAULT_PLACE_COVER, "适合连接巴伐利亚城堡、湖区和阿尔卑斯路线。", ["城市", "城堡"], ["玛ien广场", "英国花园", "新天鹅堡"]],
    ["CH-ZRH", "苏黎世", "Zurich", "CH", DEFAULT_PLACE_COVER, "瑞士城市门户，湖区、老城和火车转场都方便。", ["湖区", "城市"], ["苏黎世湖", "班霍夫大街", "老城区"]],
    ["CH-INT", "因特拉肯", "Interlaken", "CH", DEFAULT_PLACE_COVER, "雪山、湖区和徒步体验集中，适合阿尔卑斯主题。", ["雪山", "湖区"], ["少女峰", "布里恩茨湖", "哈德昆观景台"]],
    ["AT-VIE", "维也纳", "Vienna", "AT", DEFAULT_PLACE_COVER, "宫殿、音乐和咖啡馆组成奥地利城市核心。", ["宫殿", "音乐"], ["美泉宫", "金色大厅", "霍夫堡"]],
    ["AT-SZG", "萨尔茨堡", "Salzburg", "AT", DEFAULT_PLACE_COVER, "古城、城堡和湖区短线适合慢游。", ["古城", "湖区"], ["萨尔茨堡城堡", "米拉贝尔花园", "哈尔施塔特"]],
    ["DK-CPH", "哥本哈根", "Copenhagen", "DK", DEFAULT_PLACE_COVER, "设计、运河和童话气质明显，适合北欧城市线。", ["设计", "运河"], ["新港", "小美人鱼", "趣伏里公园"]],
    ["HR-DBV", "杜布罗夫尼克", "Dubrovnik", "HR", DEFAULT_PLACE_COVER, "亚得里亚海古城代表，城墙和海景很有记忆点。", ["古城", "海岸"], ["杜布罗夫尼克城墙", "斯特拉顿街", "洛克鲁姆岛"]],
    ["BA-SJJ", "萨拉热窝", "Sarajevo", "BA", DEFAULT_PLACE_COVER, "多元文化和山城气质突出，适合巴尔干路线。", ["古城", "文化"], ["巴什察尔希亚", "拉丁桥", "黄堡"]],
    ["RS-BEG", "贝尔格莱德", "Belgrade", "RS", DEFAULT_PLACE_COVER, "河流交汇和城市夜生活突出，是巴尔干路线中转点。", ["城市", "河流"], ["卡莱梅格丹城堡", "圣萨瓦教堂", "斯卡达利亚"]],
    ["ME-KOT", "科托尔", "Kotor", "ME", DEFAULT_PLACE_COVER, "峡湾海岸和古城结合，适合亚得里亚海慢游。", ["海岸", "古城"], ["科托尔古城", "圣约翰堡", "科托尔湾"]],
    ["MA-MRK", "马拉喀什", "Marrakech", "MA", DEFAULT_PLACE_COVER, "市集、庭院和沙漠延伸构成摩洛哥初访核心。", ["市集", "古城"], ["德吉玛广场", "马若雷勒花园", "巴伊亚宫"]],
    ["ZA-CPT", "开普敦", "Cape Town", "ZA", DEFAULT_PLACE_COVER, "海岸、桌山和酒庄短线组合鲜明。", ["海岸", "自然"], ["桌山", "好望角", "维多利亚港"]],
    ["ZA-JNB", "约翰内斯堡", "Johannesburg", "ZA", DEFAULT_PLACE_COVER, "南非城市文化门户，适合连接历史街区和野生动物保护区。", ["城市", "文化"], ["种族隔离博物馆", "索韦托", "狮子园"]],
    ["US-NYC", "纽约", "New York", "US", DEFAULT_PLACE_COVER, "博物馆、公园、演出和街区体验密集。", ["城市", "博物馆"], ["中央公园", "大都会艺术博物馆", "时代广场"]],
    ["US-SFO", "旧金山", "San Francisco", "US", DEFAULT_PLACE_COVER, "海湾城市和公路旅行起点，适合连接西海岸。", ["城市", "自驾"], ["金门大桥", "渔人码头", "九曲花街"]],
    ["CA-VAN", "温哥华", "Vancouver", "CA", DEFAULT_PLACE_COVER, "城市、海湾和山地自然连接顺滑。", ["城市", "自然"], ["斯坦利公园", "格兰维尔岛", "卡皮拉诺吊桥"]],
    ["CA-BAN", "班夫", "Banff", "CA", DEFAULT_PLACE_COVER, "落基山和湖区风景集中，是加拿大自然线核心。", ["湖区", "国家公园"], ["露易丝湖", "梦莲湖", "硫磺山"]],
    ["MX-MEX", "墨西哥城", "Mexico City", "MX", DEFAULT_PLACE_COVER, "博物馆、古文明遗址和城市美食集中。", ["城市", "古文明"], ["国家人类学博物馆", "宪法广场", "特奥蒂瓦坎"]],
    ["BR-RIO", "里约热内卢", "Rio de Janeiro", "BR", DEFAULT_PLACE_COVER, "海滩、山海景观和城市节奏强烈。", ["海岸", "城市"], ["基督像", "糖面包山", "科帕卡巴纳海滩"]],
    ["AR-BUE", "布宜诺斯艾利斯", "Buenos Aires", "AR", DEFAULT_PLACE_COVER, "街区、剧院和探戈文化集中，适合南美城市线。", ["城市", "文化"], ["五月广场", "博卡区", "科隆剧院"]],
    ["PE-CUS", "库斯科", "Cusco", "PE", DEFAULT_PLACE_COVER, "安第斯古城和马丘比丘门户，适合徒步和古文明主题。", ["古文明", "徒步"], ["马丘比丘", "武器广场", "圣谷"]],
    ["AU-SYD", "悉尼", "Sydney", "AU", DEFAULT_PLACE_COVER, "海港、歌剧院和海滩构成澳大利亚初访画面。", ["海港", "海岸"], ["悉尼歌剧院", "海港大桥", "邦迪海滩"]],
    ["NZ-QUE", "皇后镇", "Queenstown", "NZ", DEFAULT_PLACE_COVER, "湖区、雪山和自驾体验集中，是新西兰自然线核心。", ["湖区", "雪山"], ["瓦卡蒂普湖", "格林诺奇", "米尔福德峡湾"]],
    ["ID-DPS", "巴厘岛", "Bali", "ID", DEFAULT_PLACE_COVER, "海岛、稻田、海滩和度假体验集中，是印度尼西亚初访核心。", ["海岛", "沙滩"], ["乌布", "库塔海滩", "乌鲁瓦图"]],
    ["ID-JKT", "雅加达", "Jakarta", "ID", DEFAULT_PLACE_COVER, "印尼城市门户，适合连接爪哇文化和海岛路线。", ["城市", "美食"], ["国家纪念塔", "老城", "独立广场"]],
    ["PH-MNL", "马尼拉", "Manila", "PH", DEFAULT_PLACE_COVER, "菲律宾城市门户，适合连接海岛和殖民老城。", ["城市", "海岛"], ["王城", "黎刹公园", "马尼拉湾"]],
    ["PH-CEB", "宿务", "Cebu", "PH", DEFAULT_PLACE_COVER, "海岛跳岛和潜水体验集中，适合轻松海岛假期。", ["海岛", "潜水"], ["麦哲伦十字架", "薄荷岛", "墨宝沙丁鱼风暴"]],
    ["IN-DEL", "德里", "Delhi", "IN", DEFAULT_PLACE_COVER, "印度北部门户，历史建筑和市集体验密集。", ["历史", "城市"], ["红堡", "胡马雍陵", "印度门"]],
    ["IN-JAI", "斋浦尔", "Jaipur", "IN", DEFAULT_PLACE_COVER, "拉贾斯坦邦古城代表，宫殿和堡垒画面感强。", ["古城", "宫殿"], ["风之宫殿", "琥珀堡", "城市宫殿"]],
    ["IN-AGR", "阿格拉", "Agra", "IN", DEFAULT_PLACE_COVER, "泰姬陵所在地，适合印度北部文化线。", ["历史", "古迹"], ["泰姬陵", "阿格拉堡", "月光花园"]],
    ["NP-KTM", "加德满都", "Kathmandu", "NP", DEFAULT_PLACE_COVER, "尼泊尔文化门户，古城广场和寺庙集中。", ["山地", "文化"], ["杜巴广场", "博达哈大佛塔", "帕斯帕提那神庙"]],
    ["NP-PKR", "博卡拉", "Pokhara", "NP", DEFAULT_PLACE_COVER, "湖区和喜马拉雅视野集中，适合轻徒步。", ["山地", "湖区"], ["费瓦湖", "世界和平塔", "安娜普尔纳观景"]],
    ["LK-CMB", "科伦坡", "Colombo", "LK", DEFAULT_PLACE_COVER, "斯里兰卡城市门户，适合连接古城和海岸。", ["城市", "海岸"], ["加勒菲斯绿地", "佩塔市场", "国家博物馆"]],
    ["LK-KDY", "康提", "Kandy", "LK", DEFAULT_PLACE_COVER, "中部山城和佛牙寺文化突出。", ["文化", "山地"], ["佛牙寺", "康提湖", "皇家植物园"]],
    ["LK-GAL", "加勒", "Galle", "LK", DEFAULT_PLACE_COVER, "海边古城和殖民建筑保存完整，适合慢旅行。", ["海岸", "古城"], ["加勒堡", "灯塔", "海边城墙"]],
    ["JO-AMM", "安曼", "Amman", "JO", DEFAULT_PLACE_COVER, "约旦城市门户，适合连接佩特拉和死海。", ["城市", "历史"], ["安曼城堡山", "罗马剧场", "彩虹街"]],
    ["JO-PET", "佩特拉", "Petra", "JO", DEFAULT_PLACE_COVER, "玫瑰古城遗址核心，是约旦文明主题路线重点。", ["古文明", "遗址"], ["卡兹尼神殿", "蛇道", "修道院"]],
    ["GE-TBS", "第比利斯", "Tbilisi", "GE", DEFAULT_PLACE_COVER, "高加索城市门户，老城、温泉和葡萄酒文化明显。", ["城市", "文化"], ["第比利斯老城", "硫磺浴场", "纳里卡拉要塞"]],
    ["GE-KAZ", "卡兹别克", "Kazbegi", "GE", DEFAULT_PLACE_COVER, "高加索山地视野集中，适合自然和公路旅行。", ["山地", "自驾"], ["圣三一教堂", "高加索山景", "军事公路"]],
    ["ES-SVQ", "塞维利亚", "Seville", "ES", DEFAULT_PLACE_COVER, "安达卢西亚文化核心，宫殿、广场和弗拉门戈集中。", ["文化", "建筑"], ["塞维利亚王宫", "西班牙广场", "大教堂"]],
    ["PT-OPO", "波尔图", "Porto", "PT", DEFAULT_PLACE_COVER, "河岸老城和酒窖体验突出，适合葡萄牙北部慢游。", ["老城", "美食"], ["路易一世大桥", "莱罗书店", "杜罗河"]],
    ["NL-AMS", "阿姆斯特丹", "Amsterdam", "NL", DEFAULT_PLACE_COVER, "运河、博物馆和街区漫游密集。", ["博物馆", "城市"], ["国家博物馆", "梵高博物馆", "运河带"]],
    ["BE-BRU", "布鲁塞尔", "Brussels", "BE", DEFAULT_PLACE_COVER, "欧洲城市门户，广场、漫画和啤酒文化集中。", ["城市", "美食"], ["大广场", "原子塔", "漫画墙"]],
    ["BE-BRUJ", "布鲁日", "Bruges", "BE", DEFAULT_PLACE_COVER, "中世纪水城氛围强，适合低速步行。", ["古城", "慢旅行"], ["市场广场", "钟楼", "运河"]],
    ["CZ-PRG", "布拉格", "Prague", "CZ", DEFAULT_PLACE_COVER, "古城、城堡和桥梁构成中欧经典画面。", ["古城", "历史"], ["查理大桥", "布拉格城堡", "老城广场"]],
    ["HU-BUD", "布达佩斯", "Budapest", "HU", DEFAULT_PLACE_COVER, "多瑙河、温泉和建筑夜景适合城市慢游。", ["城市", "温泉"], ["渔人堡", "国会大厦", "塞切尼温泉"]],
    ["SI-LJU", "卢布尔雅那", "Ljubljana", "SI", DEFAULT_PLACE_COVER, "斯洛文尼亚城市门户，适合连接湖区和阿尔卑斯自然。", ["城市", "自然"], ["三桥", "城堡", "中央市场"]],
    ["SI-BLD", "布莱德", "Bled", "SI", DEFAULT_PLACE_COVER, "湖心岛和阿尔卑斯山景集中，是斯洛文尼亚自然线核心。", ["湖区", "山地"], ["布莱德湖", "湖心岛", "布莱德城堡"]],
    ["IE-DUB", "都柏林", "Dublin", "IE", DEFAULT_PLACE_COVER, "文学、酒馆和城市历史适合英爱路线。", ["城市", "文化"], ["三一学院", "圣殿酒吧", "健力士仓库"]],
    ["IE-GAL", "戈尔韦", "Galway", "IE", DEFAULT_PLACE_COVER, "爱尔兰西海岸门户，适合连接悬崖和公路风景。", ["海岸", "自驾"], ["拉丁区", "莫赫悬崖", "狂野大西洋之路"]],
    ["CL-SCL", "圣地亚哥", "Santiago", "CL", DEFAULT_PLACE_COVER, "智利城市门户，适合连接安第斯山和巴塔哥尼亚。", ["城市", "山地"], ["圣克里斯托瓦尔山", "武器广场", "中央市场"]],
    ["CL-PNT", "蓬塔阿雷纳斯", "Punta Arenas", "CL", DEFAULT_PLACE_COVER, "巴塔哥尼亚门户，适合冰川和荒野自然线。", ["自然", "冰川"], ["百内国家公园", "麦哲伦海峡", "灰冰川"]],
    ["NA-WDH", "温得和克", "Windhoek", "NA", DEFAULT_PLACE_COVER, "纳米比亚城市门户，适合连接沙漠和自驾路线。", ["沙漠", "自驾"], ["市中心", "基督教堂", "纳米布沙漠入口"]],
    ["NA-SOS", "索苏斯弗莱", "Sossusvlei", "NA", DEFAULT_PLACE_COVER, "红沙丘和死亡谷景观集中，是纳米比亚沙漠核心。", ["沙漠", "自然"], ["红沙丘", "死亡谷", "纳米布沙漠"]],
    ["MA-FES", "菲斯", "Fes", "MA", DEFAULT_PLACE_COVER, "老城、手工艺和宗教建筑密集。", ["古城", "文化"], ["菲斯老城", "皮革染坊", "布日卢蓝门"]],
    ["MA-CHEF", "舍夫沙万", "Chefchaouen", "MA", DEFAULT_PLACE_COVER, "蓝城街巷适合慢旅行和色彩记忆。", ["古城", "慢旅行"], ["蓝色老城", "西班牙清真寺", "乌塔哈曼广场"]],
    ["EG-ASW", "阿斯旺", "Aswan", "EG", DEFAULT_PLACE_COVER, "尼罗河南段和神庙体验集中，适合古埃及长线。", ["古文明", "尼罗河"], ["菲莱神庙", "努比亚村", "阿布辛贝"]],
    ["FR-LYS", "里昂", "Lyon", "FR", DEFAULT_PLACE_COVER, "法国美食和老城气质突出，适合巴黎之外的城市线。", ["美食", "老城"], ["老里昂", "富维耶山", "壁画街区"]],
    ["IS-VIK", "维克", "Vik", "IS", DEFAULT_PLACE_COVER, "黑沙滩和南岸瀑布风景集中。", ["自然", "海岸"], ["黑沙滩", "迪霍拉里", "斯科加瀑布"]],
    ["IS-AKU", "阿克雷里", "Akureyri", "IS", DEFAULT_PLACE_COVER, "冰岛北部城市门户，适合环岛路线。", ["自然", "慢旅行"], ["米湖", "众神瀑布", "北部峡湾"]],
    ["NZ-WKA", "瓦纳卡", "Wanaka", "NZ", DEFAULT_PLACE_COVER, "湖区和雪山视野舒展，适合南岛慢旅行。", ["湖区", "山地"], ["瓦纳卡湖", "罗伊峰", "孤独的树"]],
    ["NZ-MTC", "库克山", "Mount Cook", "NZ", DEFAULT_PLACE_COVER, "雪山、冰川湖和徒步路线集中。", ["山地", "自然"], ["库克山", "胡克谷步道", "塔斯曼冰湖"]],
    ["AU-MEL", "墨尔本", "Melbourne", "AU", DEFAULT_PLACE_COVER, "街区、咖啡和艺术氛围适合城市慢游。", ["城市", "美食"], ["联邦广场", "菲茨罗伊", "大洋路入口"]],
    ["AU-CNS", "凯恩斯", "Cairns", "AU", DEFAULT_PLACE_COVER, "大堡礁和热带雨林门户。", ["自然", "海岛"], ["大堡礁", "库兰达雨林", "棕榈湾"]],
    ["US-LAX", "洛杉矶", "Los Angeles", "US", DEFAULT_PLACE_COVER, "西海岸城市和公路旅行起点。", ["城市", "自驾"], ["好莱坞", "圣莫尼卡", "格里菲斯天文台"]],
    ["US-LAS", "拉斯维加斯", "Las Vegas", "US", DEFAULT_PLACE_COVER, "适合连接峡谷和西南公路旅行。", ["城市", "沙漠"], ["拉斯维加斯大道", "胡佛水坝", "大峡谷入口"]],
    ["US-ANC", "安克雷奇", "Anchorage", "US", DEFAULT_PLACE_COVER, "阿拉斯加自然门户，适合冰川、极光和野生动物路线。", ["自然", "极光"], ["楚加奇山", "冰川", "阿拉斯加铁路"]],
    ["CA-YYC", "卡尔加里", "Calgary", "CA", DEFAULT_PLACE_COVER, "落基山门户，适合连接班夫和贾斯珀。", ["城市", "山地"], ["卡尔加里塔", "牛仔节", "落基山入口"]],
    ["CA-YUL", "蒙特利尔", "Montreal", "CA", DEFAULT_PLACE_COVER, "法语文化、美食和老城街区集中。", ["城市", "文化"], ["老蒙特利尔", "皇家山", "圣母大教堂"]],
    ["MX-CUN", "坎昆", "Cancun", "MX", DEFAULT_PLACE_COVER, "加勒比海滩和玛雅遗址门户。", ["沙滩", "古文明"], ["坎昆海滩", "图卢姆", "奇琴伊察"]],
    ["PE-LIM", "利马", "Lima", "PE", DEFAULT_PLACE_COVER, "秘鲁城市门户，美食和海岸城市感突出。", ["城市", "美食"], ["米拉弗洛雷斯", "历史中心", "拉尔科博物馆"]],
    ["BR-SAO", "圣保罗", "Sao Paulo", "BR", DEFAULT_PLACE_COVER, "博物馆、美食和城市文化密集。", ["城市", "博物馆"], ["保利斯塔大道", "圣保罗艺术博物馆", "市集"]],
  ];

  function guide(intro, recommendedDays, bestSeason, budgetLevel, tags, spots) {
    return { intro, recommendedDays, bestSeason, budgetLevel, tags, spots };
  }

  function unique(values) {
    return [...new Set(values.filter(Boolean))];
  }

  const cityIdsByCountry = CITY_ROWS.reduce((groups, [id, , , countryId]) => {
    groups[countryId] = [...(groups[countryId] || []), id];
    return groups;
  }, {});

  const DEFAULT_COUNTRIES = COUNTRY_ROWS.map(([id, name, englishName, continent, cover]) => {
    const guideData = GUIDE_BY_COUNTRY[id] || guide(`${name}适合作为${continent}旅行收藏目的地。`, "4-8天", "按路线季节选择", "中等", [continent, "目的地"], []);
    return {
      id,
      name,
      englishName,
      continent,
      cover: countryPhoto(id, cover, continent, name, englishName),
      ...guideData,
      cityIds: cityIdsByCountry[id] || [],
      keywords: unique([id, name, englishName, continent, ...(guideData.tags || []), ...(guideData.spots || []), ...(cityIdsByCountry[id] || [])]),
      searchText: unique([id, name, englishName, continent, ...(guideData.tags || []), ...(guideData.spots || []), ...(cityIdsByCountry[id] || [])]).join(" "),
    };
  });

  const DEFAULT_CITIES = CITY_ROWS.map(([id, name, englishName, countryId, cover, intro, tags, spots]) => ({
    id,
    name,
    englishName,
    countryId,
    cover: CITY_PHOTOS[id] || countryRasterPhoto(countryId) || (!needsRealPhoto(cover) ? cover : REAL_PHOTOS.default),
    intro,
    tags,
    spots: spots.slice(0, 5),
    keywords: unique([id, name, englishName, countryId, intro, ...tags, ...spots]),
    searchText: unique([id, name, englishName, countryId, intro, ...tags, ...spots]).join(" "),
  }));

  const api = {
    DEFAULT_TRIP_COVER,
    DEFAULT_PLACE_COVER,
    DEFAULT_COUNTRIES,
    DEFAULT_CITIES,
  };

  if (typeof module !== "undefined" && module.exports) module.exports = api;
  global.TravelData = api;
})(typeof window !== "undefined" ? window : globalThis);
